### PR TITLE
Fix docstring

### PR DESCRIPTION
**Pull request by carlthome**
Match actual argument name in docstring.

### CODE REVIEW

**Comment by carlthome** [comment]
Unrelated error on main?

**Review by JadeCopet — APPROVED** [review]
Thanks!

**Comment by JadeCopet** [comment]
Hi, if you can take the last changes from main, this would allow to fix the CI and merge the PR. Thanks

**Comment by carlthome** [comment]
No, sorry, don't have time nor interest in doing that. Think you should rethink how you accept community contributions.

**Comment by JadeCopet** [comment]
Ok i understand. Thanks for your contribution and time.

**Pull request closed without merging**
