### PR TITLE
Model can be loaded from local directory

### PR DESCRIPTION
**Pull request by sungeuns**
Currently model only loaded from HF model hub.

Allow model loading from local directory

### CODE REVIEW

**Review by adefossez — APPROVED** [review]

**Comment by adefossez** [comment]
@sungeuns you must sign the CLA.

**Comment by MrlolDev** [comment]
Any update?

**Comment by sungeuns** [comment]
@adefossez I signed CLA, BTW do I need to pass linter?

**Comment by MrlolDev** [comment]
@sungeuns I thinkyes

**Comment by sungeuns** [comment]
@adefossez I applied flake8 linter

**Comment by MrlolDev** [comment]
When will be this merged?

**Comment by MrlolDev** [comment]
@sungeuns could you also add an example in the readme docs?

**Comment by allen-studio** [comment]
Looking forward to this feature, waiting to be merged lol

**Comment by MrlolDev** [comment]
any update?

**Comment by Gurupra5ad** [comment]
> @sungeuns could you also add an example in the readme docs?

Could you please add the documentation to a readme file ?

**Pull request merged**
