### PR TITLE
Fix musigen app memory issue

### PR DESCRIPTION
**Pull request by Harushii18**
Fixes 2 issues:

- There was a memory issue where models stayed in memory when models were changed. To replicate the issue: when the model was changed  from melody to the medium model, the melody model would remain in memory whilst the medium model was also loaded into memory, consuming large amounts of RAM. 

-  Once someone clicked the submit button, the old temp files were not removed and stayed on disk (until lifetime was reached). Added another function in the filecleaner to remove these files since they cannot be accessed from the UI anyway once someone regenerates their samples.

### CODE REVIEW

**Comment by adefossez** [comment]
I'm not sure how the deletion of all files would play out with the public demo.

**Comment by adefossez** [comment]
I dont think you can call this delete_all in the context of the public demo so we will not accept this PR as is. We can accept the deletion of the previous model prior to loading the new one though.

I'm not sure why the delete_all would help compared with the previous mechanism that delete the files after some time ?

**Comment by Harushii18** [comment]
> I dont think you can call this delete_all in the context of the public demo so we will not accept this PR as is. We can accept the deletion of the previous model prior to loading the new one though.
> 
> I'm not sure why the delete_all would help compared with the previous mechanism that delete the files after some time ?

Thank you for responding! I added that as once someone clicks the submit button again, the temp files can't be accessed from the UI: only unless someone navigates to that directory manually. So just seemed better to remove it. 
However you are right, as it does seem like that part would conflict on the public demo since it might remove other peoples' temp files that they are still accessing.

Will remove those parts.

**Comment by felixkreuk** [comment]
LGTM! Thanks for contributing @Harushii18!

**Pull request merged**
