### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by tkocou**
Added an installation script for Linux based systems (local use)

### CODE REVIEW

**Comment by tkocou** [comment]
If you think that it will detract from the installation process, perhaps ASCII art should be removed.

**Comment by ashleykleynhans** [comment]
> If you think that it will detract from the installation process, perhaps ASCII art should be removed. The nice aspect of the script is that all bits and pieces of audiocraft are automatically updated each time the script is ran. Your decision as to whether to merge it with main or to not do so.

I agree that the ASCII art makes the project look a bit amateurish, rather remove it for a cleaner, simpler installation process.

**Comment by tkocou** [comment]
It has been removed. A newer file has been uploaded.

**Comment by ashleykleynhans** [comment]
> BTW, I contacted [cla@meta.com](mailto:cla@meta.com). "_You don’t need a Facebook account to sign a CLA. You simply need a GitHub account under which you would want to contribute to our open source repos._" So where do I go for the CLA?

Click the `Details` link next to `Facebook CLA Check` in the box that says `2 workflows awaiting approval`.

**Comment by tkocou** [comment]
Thank you for the link. Go ahead and close the request.

**Pull request closed without merging**
