### PR TITLE
MusicGen-Style

### PR DESCRIPTION
**Pull request by simonrouard**
- Add a Style Conditioner as well as the training code for MusicGen-Style
- The associated website to this paper is https://musicgenstyle.github.io/

### CODE REVIEW

**Comment by nateraw** [comment]
Hi there @simonrouard any reason you closed this? :) lotta folks been looking for this implementation. Thanks either way!

**Comment by simonrouard** [comment]
Hi @nateraw, the Pull Request is incomplete but should be released by the end of the week!

**Review by JadeCopet — APPROVED** [review]
Thanks Simon!

**Comment by simonrouard** [comment]
Fix the environment requirements.
Add of MusicGen Style paper

**Pull request merged**
